### ISSUE TITLE
Is there an easy way to use it or cli?

### ISSUE THREAD

**Issue by philosofonusus** [sek-consulting/solid-ui-components#2]

**Comment by sek-consulting** [comment]
Hi @philosofonusus,

the easiest way to manually copy the components like you can do with shadcn/ui.
So you just copy the .tsx files you need from src/components into your project and install @kobalte/core with (p)npm/yarn.

I'm currently in the process of rewriting the site with solid-start since I have to much errors with astro.
Looks like I should add a installation section somewhere in there :)

If you have more questions or need a more indepth description just let me know.

**Comment by philosofonusus** [comment]
Ok, thank you, that's what I have done just wanted to know if there is a cli adaption
