### ISSUE TITLE
Install

### ISSUE THREAD

**Issue by JericoFX** [sek-consulting/solid-ui-components#8]
Hi im new in the solidjs world and i found this repo here that i really like it, how i can use it?

**Comment by sek-consulting** [comment]
Hi @JericoFX,
thanks for checking out this repo :) 

Looks like I should finally add a installation section to the docs to make it easier.
Currently there is a PR for a CLI to help you install the components you need but for now there is only the manuall way.

There are some pre-requisites before adding the components:
- `pnpm install @kobalte/core`
- make sure you have the following function in [~/lib/utils.ts](https://github.com/sek-consulting/solid-ui-components/blob/main/src/lib/utils.ts) (`pnpm install clsx tailwind-merge class-variance-authority`)
```ts
export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs))
}
```
- if your component uses icons you need to copy [~/components/icons.tsx](https://github.com/sek-consulting/solid-ui-components/blob/main/src/components/icons.tsx) into your project (or switch to another icon repo if you like)


Then just copy the component you like to use to your project.
Like if you would love to use the buttons just copy [~/components/ui/button.tsx](https://github.com/sek-consulting/solid-ui-components/blob/main/src/components/ui/button.tsx).

I really hope this already helps enough so that you can start developing :)
